Staging tests
interlay/interbtc-api pull request #337
Opened 2021-11-24 09:30 UTC by ns212

2021-11-24 10:09 UTC, nud3l commented on .env.staging
>  # TODO: Set the following values
If the values below are OK, please remove the TODO note

2022-01-12 05:31 UTC, nud3l commented
@ns212 @savudani8 should we rerun the tests here and merge or how do you want to proceed?

2022-01-24 14:43 UTC, savudani8 commented
@ns212  Not sure it's actually `source`-ing the env file, it's logging this: `2022-01-24 14:38:18          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed`

2022-01-24 14:54 UTC, savudani8 requested changes
Maybe `set -a` before sourcing the env file?

2022-07-21 09:11 UTC, closed without merging